#!/bin/bash

echo "Welcome to Redwall Component Module Setup (RCMS)";
echo "Please, what's the project name?"
read PROJECTNAME
echo "Nice. Now, what's the github repository of it?"
read PROJECTREPO
echo "Great! Le'ts create the environment..."
PROJECTFOLDER=/home/$USER/Development/
mkdir -p $PROJECTFOLDER
PROJECTFOLDER=/home/$USER/Development/$PROJECTNAME
yarn create react-app $PROJECTFOLDER
cd $PROJECTFOLDER
rm src/*
cd src
curl -o index.js https://redwall.sfo2.digitaloceanspaces.com/index-RCMS.js
mkdir lib
cd lib
echo "//Dont forget to import and export your components here!" > index.js
cd $PROJECTFOLDER

# Modify package.json
rm package.json
curl -o package.json https://redwall.sfo2.digitaloceanspaces.com/package-RCMS.json
sed -i "s/{{projectname}}/$PROJECTNAME/" package.json
yarn

# Set up transpilation
echo '{ "presets": [["react-app", { "absoluteRuntime": false }]] }' > .babelrc

# Set up linting
echo '{ "extends": "react-app" }' > .eslintrc

# Rewite the README
echo "# $PROJECTNAME  " > README.md

cd $PROJECTFOLDER
git init

git add .
git commit -m "First commit created by RCMS."

git remote add origin $PROJECTREPO
clear
echo "DONE! Let's start coding."
yarn start
