#!/bin/bash

echo "Welcome to Redwall Component Module Setup (RCMS)";
echo "Please, what's the project name?"
read PROJECTNAME
echo "Nice. Let's create the environment... "
PROJECTFOLDER=/home/$USER/Development/$PROJECTNAME

# Initialize the project
npx create-react-app $PROJECTFOLDER
cd $PROJECTFOLDER

# Generate the template
rm src/*
cd src
curl -o index.js https://redwall.sfo2.digitaloceanspaces.com/index-RCMS.js
mkdir lib
cd lib
echo "//Dont forget to import and export your components here!" > index.js
cd $PROJECTFOLDER

# Modify package.json
rm package.json
curl -o package.json https://redwall.sfo2.digitaloceanspaces.com/package-RCMS.json
sed -i "s/{{projectname}}/$PROJECTNAME/" package.json
npm install

# Set up transpilation
echo '{ "presets": [["react-app", { "absoluteRuntime": false }]] }' > .babelrc

# Set up linting
echo '{ "extends": "react-app" }' > .eslintrc

# Rewite the README
echo "# $PROJECTNAME  " > README.md

cd $PROJECTFOLDER
clear
echo "DONE! Let's start coding."
npm run start
