#!/bin/bash

echo "Welcome to Create Redwall Component Module Setup (CRCM)";
echo "Please, what's the project name?"
read PROJECTNAME
echo "Nice. Now, what's the remote git repository URL of it?"
read PROJECTREPO
echo "Great! Let's create the environment component module structure."

PROJECTFOLDER=/home/$USER/Development/
mkdir -p $PROJECTFOLDER
PROJECTFOLDER=/home/$USER/Development/$PROJECTNAME

yarn create react-app $PROJECTFOLDER

cd $PROJECTFOLDER
rm src/*
cd src
curl -o index.js https://redwall.sfo2.digitaloceanspaces.com/index-RCMS.js
mkdir lib
cd lib
printf "import ItsWorking from './components/ItsWorking'\n\nexport {ItsWorking}" > index.js
mkdir -p {components,assets/fonts}
printf "import styled from 'styled-components'\nexport export const ItsWokingStyled = styled.h1\`\ntext-align: center;color: #E21306;\n\`" > components/Style.js
printf "import React, {Component} from 'react'\nimport {ItsWokingStyled} from './Style'\n\nconst ItsWorking = () => (<ItsWorkingStyled>It's Working. (Made by Redwall Solutions)</ItsWokingStyled>)\n\nexport default ItsWorking" > components/ItsWorking.js
cd $PROJECTFOLDER

rm package.json
curl -o package.json https://redwall.sfo2.digitaloceanspaces.com/package-RCMS.json
sed -i "s/{{projectname}}/$PROJECTNAME/" package.json

yarn
yarn add styled-components

echo '{ "presets": [["react-app", { "absoluteRuntime": false }]] }' > .babelrc
echo '{ "extends": "react-app" }' > .eslintrc

echo "# $PROJECTNAME  " > README.md

cd $PROJECTFOLDER

git init
git add .
git commit -m "First commit created by CRCM."
git remote add origin $PROJECTREPO

printf "DONE! Let's start coding.\nTry cd ${PROJECTFOLDER}\nyarn start\n"
